# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('stagename', models.CharField(max_length=40)),
                ('sex', models.IntegerField()),
                ('birthday', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('plays', models.IntegerField()),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Music_song', to='music.Music')),
            ],
        ),
        migrations.CreateModel(
            name='RecordCompany',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=8)),
                ('passwd', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_user', to='music.User'),
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Album_album', to='music.Musician'),
        ),
        migrations.AddField(
            model_name='music',
            name='composer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Musician_composer', to='music.Musician'),
        ),
        migrations.AddField(
            model_name='music',
            name='lyricist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Musician_lyricist', to='music.Musician'),
        ),
        migrations.AddField(
            model_name='album',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecordCompany_company', to='music.RecordCompany'),
        ),
    ]
