# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170305_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Musician_singer', to='music.Musician'),
        ),
    ]
